# This is a basic workflow to help you get started with Actions
name: CI
env:
  VERSION: ${env.github_ref}

# Controls when the workflow will run
on: [ push ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get tag name
        run: echo "REF_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      
      - name: Debug
        run: echo ${{ env.REF_NAME }}
